"""Add order_notifications table

Revision ID: 218e76580f14
Revises: b8d9c1a7e2f0
Create Date: 2026-04-09 15:58:42.068886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '218e76580f14'
down_revision: Union[str, Sequence[str], None] = 'b8d9c1a7e2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_notifications_order_id'), 'order_notifications', ['order_id'], unique=False)
    op.alter_column('invite_codes', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('seller', 'warehouse', 'admin', 'owner', name='user_role', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invite_codes', 'role',
               existing_type=sa.Enum('seller', 'warehouse', 'admin', 'owner', name='user_role', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_order_notifications_order_id'), table_name='order_notifications')
    op.drop_table('order_notifications')
    # ### end Alembic commands ###
