"""Increase stock_movements enum length

Revision ID: 25444190f66e
Revises: f5f92ac15da3
Create Date: 2026-04-13 11:19:41.825068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25444190f66e'
down_revision: Union[str, Sequence[str], None] = 'f5f92ac15da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_movements', 'movement_type',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.Enum('receive_from_supplier', 'dispatch_to_store', 'return_to_warehouse', 'sale', 'display_dispatch', 'display_receive', 'display_return', 'dispatch_to_wholesaler', name='stock_movement_type', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_movements', 'movement_type',
               existing_type=sa.Enum('receive_from_supplier', 'dispatch_to_store', 'return_to_warehouse', 'sale', 'display_dispatch', 'display_receive', 'display_return', 'dispatch_to_wholesaler', name='stock_movement_type', native_enum=False),
               type_=sa.VARCHAR(length=21),
               existing_nullable=False)
    # ### end Alembic commands ###
