"""Add batch_id to orders

Revision ID: 31f8493b1970
Revises: faf1570c5d61
Create Date: 2026-03-18 11:21:28.736083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f8493b1970'
down_revision: Union[str, Sequence[str], None] = 'faf1570c5d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('batch_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_orders_batch_id'), 'orders', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_batch_id'), table_name='orders')
    op.drop_column('orders', 'batch_id')
    # ### end Alembic commands ###
