"""add_display_transfer_stock_receive_enum

Revision ID: 63ccf976ab61
Revises: b9aacd02643f
Create Date: 2026-03-04 11:02:40.174797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ccf976ab61'
down_revision: Union[str, Sequence[str], None] = 'b9aacd02643f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add new values to transaction_type enum."""
    op.execute("ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'display_transfer'")
    op.execute("ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'stock_receive'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
