"""add_main_warehouse_and_fix_enums

Revision ID: 6d86d3d24828
Revises: 39edb0dca9b1
Create Date: 2026-04-02 10:27:24.325955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d86d3d24828'
down_revision: Union[str, Sequence[str], None] = '39edb0dca9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ── Seed data: Главный склад ─────────────────────────────────────────────
    stores_table = sa.table(
        "stores",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("address", sa.String),
        sa.column("store_type", sa.String),
        sa.column("is_active", sa.Boolean),
        sa.column("current_debt", sa.Numeric),
    )
    op.bulk_insert(
        stores_table,
        [
            {
                "name": "Главный Склад",
                "address": "Центральный офис",
                "store_type": "warehouse",
                "is_active": True,
                "current_debt": 0,
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
