"""Add PushSubscription model

Revision ID: b750b0983bdf
Revises: b87f87dd2c01
Create Date: 2026-05-31 18:01:59.238887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b750b0983bdf'
down_revision: Union[str, Sequence[str], None] = 'b87f87dd2c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_notifications_backup_before_clear_20260517_0416')
    op.drop_table('stock_movements_zero_prefix_merge_backup_20260517_1139')
    op.drop_table('product_zero_prefix_merge_backup_20260517_1139')
    op.drop_table('stores_debt_backup_before_clear_20260517_0418')
    op.drop_table('supplier_invoices_backup_before_clear_20260517_0418')
    op.drop_table('sales_backup_before_hard_delete_20260517_1045')
    op.drop_table('supplier_return_items_backup_before_clear_20260517_0418')
    op.drop_table('sales_backup_before_clear_20260517_0418')
    op.drop_table('inventory_merge_backup_2103_to_02103_20260517_1137')
    op.drop_table('supplier_outgoing_returns_backup_before_clear_20260517_0418')
    op.drop_table('display_inventory_merge_backup_2103_to_02103_20260517_1137')
    op.drop_table('supplier_return_items_backup_before_hard_delete_20260517_1045')
    op.drop_table('supplier_returns_backup_before_clear_20260517_0418')
    op.drop_table('display_inventory_backup_before_clear_20260517_0415')
    op.drop_table('inventory_zero_prefix_merge_backup_20260517_1139')
    op.drop_table('sales_order_links_backup_before_clear_20260517_0416')
    op.drop_table('supplier_payouts_backup_before_clear_20260517_0418')
    op.drop_table('supplier_invoice_items_backup_before_clear_20260517_0418')
    op.drop_table('display_inventory_star_sku_backup_20260507_0520')
    op.drop_table('inventory_backup_before_min5_warehouse_20260517_1406')
    op.drop_table('supplier_outgoing_return_items_backup_before_hard_delete_202605')
    op.drop_table('inventory_backup_before_clear_20260517_0415')
    op.drop_table('orders_backup_before_hard_delete_20260517_1045')
    op.drop_table('products_backup_before_hard_delete_20260517_1045')
    op.drop_table('orders_backup_before_clear_20260517_0416')
    op.drop_table('products_star_sku_backup_20260507_0520')
    op.drop_table('supplier_receipts_backup_before_clear_20260517_0418')
    op.drop_table('supplier_outgoing_return_items_backup_before_clear_20260517_041')
    op.drop_table('debt_ledgers_backup_before_clear_20260517_0418')
    op.drop_table('products_backup_before_deactivate_20260517_0416')
    op.drop_table('supplier_invoice_items_backup_before_hard_delete_20260517_1045')
    op.drop_table('supplier_receipt_items_backup_before_hard_delete_20260517_1045')
    op.drop_table('display_inventory_zero_prefix_merge_backup_20260517_1139')
    op.drop_table('financial_transactions_backup_before_clear_20260517_0418')
    op.drop_table('order_notifications_backup_before_hard_delete_20260517_1045')
    op.drop_table('stock_movements_backup_before_hard_delete_20260517_1045')
    op.drop_table('display_inventory_backup_before_hard_delete_20260517_1045')
    op.drop_table('stock_movements_merge_backup_2103_to_02103_20260517_1137')
    op.drop_table('product_merge_backup_2103_to_02103_20260517_1137')
    op.drop_table('supplier_receipt_items_backup_before_clear_20260517_0418')
    op.drop_table('supplier_payments_backup_before_clear_20260517_0418')
    op.drop_table('inventory_backup_before_hard_delete_20260517_1045')
    op.drop_table('suppliers_backup_before_clear_20260517_0418')
    op.alter_column('debt_ledgers', 'reason',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('sale_completed', 'cash_collection', 'return_approved', 'delivery_accepted', name='debt_ledger_reason', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('ix_sales_order_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_store_created_at'), table_name='sales')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sales_store_created_at'), 'sales', ['store_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sales_order_id'), 'sales', ['order_id'], unique=False)
    op.alter_column('debt_ledgers', 'reason',
               existing_type=sa.Enum('sale_completed', 'cash_collection', 'return_approved', 'delivery_accepted', name='debt_ledger_reason', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_table('suppliers_backup_before_clear_20260517_0418',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contact_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('inventory_backup_before_hard_delete_20260517_1045',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('supplier_payments_backup_before_clear_20260517_0418',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('supplier_receipt_items_backup_before_clear_20260517_0418',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_unit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('product_merge_backup_2103_to_02103_20260517_1137',
    sa.Column('source_table', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('store_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('stock_movements_merge_backup_2103_to_02103_20260517_1137',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('movement_type', sa.VARCHAR(length=22), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('display_inventory_backup_before_hard_delete_20260517_1045',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('stock_movements_backup_before_hard_delete_20260517_1045',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('movement_type', sa.VARCHAR(length=22), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('order_notifications_backup_before_hard_delete_20260517_1045',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('financial_transactions_backup_before_clear_20260517_0418',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('display_inventory_zero_prefix_merge_backup_20260517_1139',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('supplier_receipt_items_backup_before_hard_delete_20260517_1045',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_unit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('supplier_invoice_items_backup_before_hard_delete_20260517_1045',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_unit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('products_backup_before_deactivate_20260517_0416',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('store_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('debt_ledgers_backup_before_clear_20260517_0418',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount_change', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('supplier_outgoing_return_items_backup_before_clear_20260517_041',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('return_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_unit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('supplier_receipts_backup_before_clear_20260517_0418',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('products_star_sku_backup_20260507_0520',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(length=120), autoincrement=False, nullable=True)
    )
    op.create_table('orders_backup_before_clear_20260517_0416',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_item', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('batch_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('products_backup_before_hard_delete_20260517_1045',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('store_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('orders_backup_before_hard_delete_20260517_1045',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_item', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('batch_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('inventory_backup_before_clear_20260517_0415',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('supplier_outgoing_return_items_backup_before_hard_delete_202605',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('return_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_unit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('inventory_backup_before_min5_warehouse_20260517_1406',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('display_inventory_star_sku_backup_20260507_0520',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('supplier_invoice_items_backup_before_clear_20260517_0418',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_unit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('supplier_payouts_backup_before_clear_20260517_0418',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('sales_order_links_backup_before_clear_20260517_0416',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('inventory_zero_prefix_merge_backup_20260517_1139',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('display_inventory_backup_before_clear_20260517_0415',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('supplier_returns_backup_before_clear_20260517_0418',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('supplier_return_items_backup_before_hard_delete_20260517_1045',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('return_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_unit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('display_inventory_merge_backup_2103_to_02103_20260517_1137',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('supplier_outgoing_returns_backup_before_clear_20260517_0418',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('inventory_merge_backup_2103_to_02103_20260517_1137',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('sales_backup_before_clear_20260517_0418',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_item', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('supplier_return_items_backup_before_clear_20260517_0418',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('return_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_unit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('sales_backup_before_hard_delete_20260517_1045',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_item', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('supplier_invoices_backup_before_clear_20260517_0418',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('stores_debt_backup_before_clear_20260517_0418',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_debt', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('product_zero_prefix_merge_backup_20260517_1139',
    sa.Column('source_table', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('store_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('stock_movements_zero_prefix_merge_backup_20260517_1139',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('movement_type', sa.VARCHAR(length=22), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('order_notifications_backup_before_clear_20260517_0416',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
